# Generated by Django 5.2.7 on 2025-11-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='grade',
        ),
        migrations.AddField(
            model_name='studentdata',
            name='courses',
            field=models.ManyToManyField(to='students.course'),
        ),
    ]
