# Generated by Django 5.2.7 on 2025-11-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_studentdata_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
