# Generated by Django 6.0 on 2025-12-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_studentdata_student_delete_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='students.course'),
        ),
    ]
